emacsd init file added

diff --git a/emacsd b/emacsd
--- a/emacsd
+++ b/emacsd
@@ -1,14 +1,14 @@
 #!/bin/sh
-#;;; see page http://www.emacswiki.org/emacs/emacsd for discussion and usage
+# ;;; see page http://www.emacswiki.org/emacs/emacsd for discussion and usage
 
 ### BEGIN INIT INFO
-# Provides: emacsd
-# Required-Start: $remote_fs $syslog
-# Required-Stop: $remote_fs $syslog
-# Default-Start: 2 3 4 5
-# Default-Stop: 0 1 6
+# Provides:          emacsd
+# Required-Start:    $remote_fs $syslog
+# Required-Stop:     $remote_fs $syslog
+# Default-Start:     2 3 4 5
+# Default-Stop:      0 1 6
 # Short-Description: Start emacsd at boot time
-# Description: Enable service provided by daemon.
+# Description:       Enable service provided by daemon.
 ### END INIT INFO
 
 # Local Settings
@@ -40,11 +40,11 @@ socket_file="/tmp/emacs${emacsd_uid}/server"
 
 if [ "$1" = "start" ]
 then
-        #check whether already started
+    #check whether already started
     if [ -e "$socket_file" ]
     then
-	echo "Error: emacsd already started."
-	exit $EE_EMACSD_ALREADY_STARTED
+        echo "Error: emacsd already started."
+        exit $EE_EMACSD_ALREADY_STARTED
     fi
 
     echo "Start emacs daemon ..."
@@ -52,37 +52,37 @@ then
 
     if [ "$?" -eq 0 ]
     then
-	echo "emacsd is up."
-	exit 0
+        echo "emacsd is up."
+        exit 0
     else
-	echo "Error: emacsd failed to start."
-	exit $EE_EMACS_FAIL_TO_START
+        echo "Error: emacsd failed to start."
+        exit $EE_EMACS_FAIL_TO_START
     fi
 fi
 
 if [ "$1" = "stop" ]
 then
-        #options="-s $socket_file"
+    #options="-s $socket_file"
     options=""
     lispcode="(kill-emacs)"
     sudo -u"#"$emacsd_uid $emacsclient $options --eval $lispcode
 
     if [ "$?" -eq 0 ]
     then
-	echo "emacsd is down."
-	exit 0
+        echo "emacsd is down."
+        exit 0
     else
-	echo "Error: emacsd failed to stop."
-	exit $EE_EMACS_FAIL_TO_STOP
+        echo "Error: emacsd failed to stop."
+        exit $EE_EMACS_FAIL_TO_STOP
     fi
     exit 0
 fi
 
-if [ "$1" = "restart" ] || [ "$1" = "force-reload" ]
+if [ "$1" = "restart" ] || [ "$1" = "force-reload" ] 
 then
     if [ -e "$socket_file" ]
     then
-	$0 stop
+        $0 stop
     fi
     $0 start
 fi
@@ -95,4 +95,3 @@ then
 fi
 
 exit 0
-
